### ISSUE TITLE
Parameter values with incorrect exponential format are read without error

### ISSUE THREAD

**Issue by mbedward** [pzylstra/ffm_cpp#1]
Prototype Scala version of the model reports the following error reading test parameter file 11a.txt:

> Failed to parse input near live leaf moisture =   100e-2, 100-2

The C++ version reads this file without complaint but if used, the second value would be converted to 100.0 rather than 1.0

**Comment by pzylstra** [comment]
Hi Michael,

It looks like the second parameter is an erroneous entry that should be 100e-2, I prefer the error message that Scala gives I think.

Phil

**Comment by mbedward** [comment]
Yes - just using the github issue tracker to keep a record of glitches in the C++ code discovered during testing of the Scala version.
