### ISSUE TITLE
Stratum gaps miscalculation in monte carlo

### ISSUE THREAD

**Issue by pzylstra** [pzylstra/ffm_cpp#3]
Including stratum gaps in the settings of an input file causes the model to consider the stratum empty of plants for a number of instances equal to (1 - percent cover). 

The NS stratum in the input file Gaps.txt has 14% cover, so approximately 6 out of 7 runs should model behaviour as if no plants exist in that stratum. As the output file gap.csv shows however, the NS stratum is almost never ignited. This is not reflective of the fire behaviour calculation; when gaps are turned off (No_gap.txt), the stratum is ignited every time (nogap.csv).

[Stratum_gaps.zip](https://github.com/pzylstra/ffm_cpp/files/100355/Stratum_gaps.zip)

**Comment by mbedward** [comment]
Just had an initial look at this, following the program in the debugger:

The inclusion of the stratum based on cover seems to be working correctly - although cover being another random variable makes this potentially precarious.

Followed a case where near surface stratum was included and confirmed that it was properly included in the ignition path simulation, and that ignited segments and flames resulted.

Possibly there is some problem further down the chain, e.g. when collecting the outputs for reporting. Need to spend more time on it.

**Comment by mbedward** [comment]
Treating this as fixed for the moment
